import { mustAuth } from '#/middleware/auth';
import {Router} from 'express';
import { updateFollower, getUploads, getPublicUploads , getPublicProfile, getPublicPlaylist, getRecommendByProfile, getAutoGeneratedPlaylist, getFollowersProfile,  getFollowingsProfile, getFollowersProfilePublic, getPlaylistAudios, getPrivatePlaylistAudios, getIsFollowing } from '../controllers/profile';
import { isAuth } from '../middleware/auth';


const router = Router();


router.post("/update-follower/:profileId", mustAuth,updateFollower)
router.get("/upload", mustAuth, getUploads)
router.get("/upload/:profileId", getPublicUploads)
router.get("/info/:profileId", getPublicProfile)
router.get("/playlist/:profileId", getPublicPlaylist)
router.get("/recommended", isAuth, getRecommendByProfile)
router.get("/auto-generated-playlist", mustAuth, getAutoGeneratedPlaylist)
router.get("/followers", mustAuth, getFollowersProfile)
router.get("/followers/:profileId", mustAuth, getFollowersProfilePublic)
router.get("/following", mustAuth, getFollowingsProfile)
router.get("/playlist-audios/:playlistId", getPlaylistAudios)
router.get("/private-playlist-audios/:playlistId", mustAuth, getPrivatePlaylistAudios)
router.get("/is-following/:profileId",mustAuth ,getIsFollowing)


export default router;