import { mustAuth } from '#/middleware/auth';
import {Router} from 'express';
import { updateFollower, getUploads, getPublicUploads , getPublicProfile, getPublicPlaylist, getRecommendByProfile, getAutoGeneratedPlaylist } from '../controllers/profile';
import { isAuth } from '../middleware/auth';


const router = Router();


router.post("/update-follower/:profileId", mustAuth,updateFollower)
router.get("/upload", mustAuth, getUploads)
router.get("/upload/:profileId", getPublicUploads)
router.get("/info/:profileId", getPublicProfile)
router.get("/playlist/:profileId", getPublicPlaylist)
router.get("/recommended", isAuth, getRecommendByProfile)
router.get("/auto-generated-playlist", isAuth, getAutoGeneratedPlaylist)

export default router;